/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oper.h"

bool_t
xdr_oper_in (XDR *xdrs, oper_in *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
