/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oper.h"


void
oper_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	long result_1;
	oper_in  soma_1_arg;
	enum clnt_stat retval_2;
	long result_2;
	oper_in  dif_1_arg;
	enum clnt_stat retval_3;
	long result_3;
	oper_in  prod_1_arg;
	enum clnt_stat retval_4;
	long result_4;
	oper_in  razao_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OPER, OPER_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = soma_1(&soma_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = dif_1(&dif_1_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = prod_1(&prod_1_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = razao_1(&razao_1_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	oper_1 (host);
exit (0);
}
