/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oper.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
oper_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		oper_in soma_1_arg;
		oper_in dif_1_arg;
		oper_in prod_1_arg;
		oper_in razao_1_arg;
	} argument;
	union {
		long soma_1_res;
		long dif_1_res;
		long prod_1_res;
		long razao_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case SOMA:
		_xdr_argument = (xdrproc_t) xdr_oper_in;
		_xdr_result = (xdrproc_t) xdr_long;
		local = (bool_t (*) (char *, void *,  struct svc_req *))soma_1_svc;
		break;

	case DIF:
		_xdr_argument = (xdrproc_t) xdr_oper_in;
		_xdr_result = (xdrproc_t) xdr_long;
		local = (bool_t (*) (char *, void *,  struct svc_req *))dif_1_svc;
		break;

	case PROD:
		_xdr_argument = (xdrproc_t) xdr_oper_in;
		_xdr_result = (xdrproc_t) xdr_long;
		local = (bool_t (*) (char *, void *,  struct svc_req *))prod_1_svc;
		break;

	case RAZAO:
		_xdr_argument = (xdrproc_t) xdr_oper_in;
		_xdr_result = (xdrproc_t) xdr_long;
		local = (bool_t (*) (char *, void *,  struct svc_req *))razao_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!oper_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (OPER, OPER_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, OPER, OPER_VERS, oper_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (OPER, OPER_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OPER, OPER_VERS, oper_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OPER, OPER_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
