/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPER_H_RPCGEN
#define _OPER_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct oper_in {
	long arg1;
	long arg2;
};
typedef struct oper_in oper_in;

#define OPER 0
#define OPER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOMA 0
extern  enum clnt_stat soma_1(oper_in *, long *, CLIENT *);
extern  bool_t soma_1_svc(oper_in *, long *, struct svc_req *);
#define DIF 1
extern  enum clnt_stat dif_1(oper_in *, long *, CLIENT *);
extern  bool_t dif_1_svc(oper_in *, long *, struct svc_req *);
#define PROD 2
extern  enum clnt_stat prod_1(oper_in *, long *, CLIENT *);
extern  bool_t prod_1_svc(oper_in *, long *, struct svc_req *);
#define RAZAO 3
extern  enum clnt_stat razao_1(oper_in *, long *, CLIENT *);
extern  bool_t razao_1_svc(oper_in *, long *, struct svc_req *);
extern int oper_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMA 0
extern  enum clnt_stat soma_1();
extern  bool_t soma_1_svc();
#define DIF 1
extern  enum clnt_stat dif_1();
extern  bool_t dif_1_svc();
#define PROD 2
extern  enum clnt_stat prod_1();
extern  bool_t prod_1_svc();
#define RAZAO 3
extern  enum clnt_stat razao_1();
extern  bool_t razao_1_svc();
extern int oper_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_oper_in (XDR *, oper_in*);

#else /* K&R C */
extern bool_t xdr_oper_in ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPER_H_RPCGEN */
